### ISSUE TITLE
Binning comboBox: update options based on data set

### ISSUE THREAD

**Issue by henrikjacobsenfys** [henrikjacobsenfys/MJOLNIR-GUI#5]
Go through all data files in data set and figure out which binnings are actually possible.

Also show the current binning somehow

**Comment by MJOLNIRPackage** [comment]
The possible binnings are shown in the drop-down menu to the top right of the DataSet manager on the main screen of the gui. If different files have different possible binnings, this will fail as it showcases the first possible binning. If a binning is selected, it is shown on to the right under data file properties. This option might be hidden but can be reactivated under settings in the file drop-down in the main tool-bar of the GUI
